version: "3"
services:
  db:
    image: mariadb:10.6.5
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env

  webserv-wordpress:
    depends_on:
      - db
    build: .
    volumes:
      - wordpress_data:/webserv/html/wordpress
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
      - "8087:8087"
      - "8088:8088"
      - "8089:8089"
      - "8090:8090"
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "9000:9000"
    restart: always
    env_file: .env
volumes:
  db_data: {}
  wordpress_data: {}
