name: Integration tests check

on:
  push:
    branches: [$default-branch]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04]
    steps:
      - name: Check out Github repository
        uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Install dependencies
        working-directory: ./srcs/app/test/integration
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run integration tests
        timeout-minutes: 2
        run: make integration_test
