name: Integration tests check

on:
  push:
    branches: [$default-branch]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04]
    steps:
      - name: Check out Github repository
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        working-directory: ./srcs/app/test/integration
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Setup test folder ownership
        working-directory: ./html/web3
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then \
          sudo su -c "useradd test_user -s /bin/bash -m"
          sudo chown -R test_user:test_user no_privileges_folder
          fi

      - name: Run integration tests
        timeout-minutes: 4
        run: make integration_test -j12
