---
name: Unit tests check

on:
    push:
        branches: [$default-branch]
    pull_request:
        types: [assigned, opened, synchronize, reopened]

jobs:
    call-build-workflow:
        uses: 42AGV/webserv/.github/workflows/compile_check_gpp.yml@${{env.GITHUB_SHA_SHORT}}
    unit_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Running unit tests...
              run: make unit_test -j12
