---
name: Unit tests check

on:
    push:
        branches: [$default-branch]
    pull_request:
        types: [assigned, opened, synchronize, reopened]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Running unit tests...
              run: make test ; make run
